repos:
  # Batch of helpful formatters and patterns
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements

  # Format code. No, I don't like everything black does either.
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  # Format docs.
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black>=22.8.0]
